/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;

namespace HelpDeskManager.Data
{
	public partial class DAOTechnician : HelpDesk_BaseData
	{
		#region member variables
		protected Int32? _id;
		protected string _name;
		protected Int32? _designationid;
		protected Int32? _roleid;
		#endregion

		#region class methods
		public DAOTechnician()
		{
		}
		///<Summary>
		///Select one row by primary key(s)
		///This method returns one row from the table technician based on the primary key(s)
		///</Summary>
		///<returns>
		///DAOTechnician
		///</returns>
		///<parameters>
		///Int32? id
		///</parameters>
		public static DAOTechnician SelectOne(Int32? id)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprtechnician_SelectOne;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("technician");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)id?? (object)DBNull.Value));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				DAOTechnician retObj = null;
				if(dt.Rows.Count > 0)
				{
					retObj = new DAOTechnician();
					retObj._id					 = Convert.IsDBNull(dt.Rows[0]["id"]) ? (Int32?)null : (Int32?)dt.Rows[0]["id"];
					retObj._name					 = Convert.IsDBNull(dt.Rows[0]["name"]) ? null : (string)dt.Rows[0]["name"];
					retObj._designationid					 = Convert.IsDBNull(dt.Rows[0]["designationid"]) ? (Int32?)null : (Int32?)dt.Rows[0]["designationid"];
					retObj._roleid					 = Convert.IsDBNull(dt.Rows[0]["roleid"]) ? (Int32?)null : (Int32?)dt.Rows[0]["roleid"];
				}
				return retObj;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete one row by primary key(s)
		///this method allows the object to delete itself from the table technician based on its primary key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprtechnician_DeleteOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)_id?? (object)DBNull.Value));

				command.ExecuteNonQuery();

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows by foreign key
		///This method returns all data rows in the table technician based on a foreign key
		///</Summary>
		///<returns>
		///IList-DAOTechnician.
		///</returns>
		///<parameters>
		///Int32? designationid
		///</parameters>
		public static IList<DAOTechnician> SelectAllByDesignationid(Int32? designationid)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprtechnician_SelectAllByDesignationid;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("technician");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(new SqlParameter("@designationid", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)designationid?? (object)DBNull.Value));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DAOTechnician> objList = new List<DAOTechnician>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOTechnician retObj = new DAOTechnician();
						retObj._id					 = Convert.IsDBNull(row["id"]) ? (Int32?)null : (Int32?)row["id"];
						retObj._name					 = Convert.IsDBNull(row["name"]) ? null : (string)row["name"];
						retObj._designationid					 = Convert.IsDBNull(row["designationid"]) ? (Int32?)null : (Int32?)row["designationid"];
						retObj._roleid					 = Convert.IsDBNull(row["roleid"]) ? (Int32?)null : (Int32?)row["roleid"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///Int32? designationid
		///</parameters>
		public static Int32 SelectAllByDesignationidCount(Int32? designationid)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprtechnician_SelectAllByDesignationidCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(new SqlParameter("@designationid", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)designationid?? (object)DBNull.Value));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete all by foreign key
		///This method deletes all rows in the table technician with a given foreign key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///HelpDesk_TxConnectionProvider connectionProvider, Int32? designationid
		///</parameters>
		public static void DeleteAllByDesignationid(HelpDesk_TxConnectionProvider connectionProvider, Int32? designationid)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprtechnician_DeleteAllByDesignationid;
			command.CommandType = CommandType.Text;
			command.Connection = connectionProvider.Connection;
			command.Transaction = connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@designationid", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)designationid?? (object)DBNull.Value));

				command.ExecuteNonQuery();

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows by foreign key
		///This method returns all data rows in the table technician based on a foreign key
		///</Summary>
		///<returns>
		///IList-DAOTechnician.
		///</returns>
		///<parameters>
		///Int32? roleid
		///</parameters>
		public static IList<DAOTechnician> SelectAllByRoleid(Int32? roleid)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprtechnician_SelectAllByRoleid;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("technician");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(new SqlParameter("@roleid", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)roleid?? (object)DBNull.Value));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DAOTechnician> objList = new List<DAOTechnician>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOTechnician retObj = new DAOTechnician();
						retObj._id					 = Convert.IsDBNull(row["id"]) ? (Int32?)null : (Int32?)row["id"];
						retObj._name					 = Convert.IsDBNull(row["name"]) ? null : (string)row["name"];
						retObj._designationid					 = Convert.IsDBNull(row["designationid"]) ? (Int32?)null : (Int32?)row["designationid"];
						retObj._roleid					 = Convert.IsDBNull(row["roleid"]) ? (Int32?)null : (Int32?)row["roleid"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///Int32? roleid
		///</parameters>
		public static Int32 SelectAllByRoleidCount(Int32? roleid)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprtechnician_SelectAllByRoleidCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(new SqlParameter("@roleid", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)roleid?? (object)DBNull.Value));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete all by foreign key
		///This method deletes all rows in the table technician with a given foreign key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///HelpDesk_TxConnectionProvider connectionProvider, Int32? roleid
		///</parameters>
		public static void DeleteAllByRoleid(HelpDesk_TxConnectionProvider connectionProvider, Int32? roleid)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprtechnician_DeleteAllByRoleid;
			command.CommandType = CommandType.Text;
			command.Connection = connectionProvider.Connection;
			command.Transaction = connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@roleid", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)roleid?? (object)DBNull.Value));

				command.ExecuteNonQuery();

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Insert a new row
		///This method saves a new object to the table technician
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Insert()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprtechnician_InsertOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _id));
				command.Parameters.Add(new SqlParameter("@name", SqlDbType.VarChar, 255, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_name?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@designationid", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_designationid?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@roleid", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_roleid?? (object)DBNull.Value));

				command.ExecuteNonQuery();

				_id					 = Convert.IsDBNull(command.Parameters["@id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@id"].Value;
				_name					 = Convert.IsDBNull(command.Parameters["@name"].Value) ? null : (string)command.Parameters["@name"].Value;
				_designationid					 = Convert.IsDBNull(command.Parameters["@designationid"].Value) ? (Int32?)null : (Int32?)command.Parameters["@designationid"].Value;
				_roleid					 = Convert.IsDBNull(command.Parameters["@roleid"].Value) ? (Int32?)null : (Int32?)command.Parameters["@roleid"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows
		///This method returns all data rows in the table technician
		///</Summary>
		///<returns>
		///IList-DAOTechnician.
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<DAOTechnician> SelectAll()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprtechnician_SelectAll;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("technician");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DAOTechnician> objList = new List<DAOTechnician>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOTechnician retObj = new DAOTechnician();
						retObj._id					 = Convert.IsDBNull(row["id"]) ? (Int32?)null : (Int32?)row["id"];
						retObj._name					 = Convert.IsDBNull(row["name"]) ? null : (string)row["name"];
						retObj._designationid					 = Convert.IsDBNull(row["designationid"]) ? (Int32?)null : (Int32?)row["designationid"];
						retObj._roleid					 = Convert.IsDBNull(row["roleid"]) ? (Int32?)null : (Int32?)row["roleid"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SelectAllCount()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprtechnician_SelectAllCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///IList-DAOTechnician.
		///</returns>
		///<parameters>
		///DAOTechnician daoTechnician
		///</parameters>
		public static IList<DAOTechnician> SelectAllBySearchFields(DAOTechnician daoTechnician)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprtechnician_SelectAllBySearchFields;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("technician");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)daoTechnician.Id?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@name", SqlDbType.VarChar, 255, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)daoTechnician.Name?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@designationid", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoTechnician.Designationid?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@roleid", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)daoTechnician.Roleid?? (object)DBNull.Value));

				staticConnection.Open();
				sqlAdapter.Fill(dt);

				List<DAOTechnician> objList = new List<DAOTechnician>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOTechnician retObj = new DAOTechnician();
						retObj._id					 = Convert.IsDBNull(row["id"]) ? (Int32?)null : (Int32?)row["id"];
						retObj._name					 = Convert.IsDBNull(row["name"]) ? null : (string)row["name"];
						retObj._designationid					 = Convert.IsDBNull(row["designationid"]) ? (Int32?)null : (Int32?)row["designationid"];
						retObj._roleid					 = Convert.IsDBNull(row["roleid"]) ? (Int32?)null : (Int32?)row["roleid"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///DAOTechnician daoTechnician
		///</parameters>
		public static Int32 SelectAllBySearchFieldsCount(DAOTechnician daoTechnician)
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprtechnician_SelectAllBySearchFieldsCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)daoTechnician.Id?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@name", SqlDbType.VarChar, 255, ParameterDirection.Input, false, 0, 0, "", DataRowVersion.Proposed, (object)daoTechnician.Name?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@designationid", SqlDbType.Int, 4, ParameterDirection.Input, true, 10, 0, "", DataRowVersion.Proposed, (object)daoTechnician.Designationid?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@roleid", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)daoTechnician.Roleid?? (object)DBNull.Value));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();

				return retCount;
			}
			catch
			{
				throw;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Update one row by primary key(s)
		///This method allows the object to update itself in the table technician based on its primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Update()
		{
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprtechnician_UpdateOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(new SqlParameter("@id", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_id?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@name", SqlDbType.VarChar, 255, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_name?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@designationid", SqlDbType.Int, 4, ParameterDirection.InputOutput, true, 10, 0, "", DataRowVersion.Proposed, (object)_designationid?? (object)DBNull.Value));
				command.Parameters.Add(new SqlParameter("@roleid", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_roleid?? (object)DBNull.Value));

				command.ExecuteNonQuery();

				_id					 = Convert.IsDBNull(command.Parameters["@id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@id"].Value;
				_name					 = Convert.IsDBNull(command.Parameters["@name"].Value) ? null : (string)command.Parameters["@name"].Value;
				_designationid					 = Convert.IsDBNull(command.Parameters["@designationid"].Value) ? (Int32?)null : (Int32?)command.Parameters["@designationid"].Value;
				_roleid					 = Convert.IsDBNull(command.Parameters["@roleid"].Value) ? (Int32?)null : (Int32?)command.Parameters["@roleid"].Value;

			}
			catch
			{
				throw;
			}
			finally
			{
				command.Dispose();
			}
		}

		#endregion

		#region member properties

		public Int32? Id
		{
			get
			{
				return _id;
			}
			set
			{
				_id = value;
			}
		}

		public string Name
		{
			get
			{
				return _name;
			}
			set
			{
				_name = value;
			}
		}

		public Int32? Designationid
		{
			get
			{
				return _designationid;
			}
			set
			{
				_designationid = value;
			}
		}

		public Int32? Roleid
		{
			get
			{
				return _roleid;
			}
			set
			{
				_roleid = value;
			}
		}

		#endregion
	}
}

#region inline sql procs
namespace HelpDeskManager.Data
{
	public partial class InlineProcs
	{
		internal static string ctprtechnician_SelectOne = @"
			-- Select one row based on the primary key(s)
			-- selects all rows from the table
			SELECT 
			[id]
			,[name]
			,[designationid]
			,[roleid]
			FROM [dbo].[technician]
			WHERE 
			[id] = @id
			";

		internal static string ctprtechnician_DeleteOne = @"
			-- Delete a row based on the primary key(s)
			-- delete all matching from the table
			DELETE [dbo].[technician]
			WHERE 
			[id] = @id
			";

		internal static string ctprtechnician_SelectAllByDesignationid = @"
			-- Select all rows based on a foreign key
			-- selects all rows from the table
			SELECT 
			[id]
			,[name]
			,[designationid]
			,[roleid]
			FROM [dbo].[technician]
			WHERE 
			[designationid] = @designationid OR ([designationid] IS NULL AND @designationid IS NULL)
			";

		internal static string ctprtechnician_SelectAllByDesignationidCount = @"
			-- Get count of rows returnable by this query
			-- selects count of all rows from the table
			SELECT COUNT(*)
			FROM [dbo].[technician]
			WHERE 
			[designationid] = @designationid OR ([designationid] IS NULL AND @designationid IS NULL)
			";

		internal static string ctprtechnician_DeleteAllByDesignationid = @"
			
			-- delete all matching from the table
			DELETE [dbo].[technician]
			WHERE 
			[designationid] = @designationid OR ([designationid] IS NULL AND @designationid IS NULL)
			";

		internal static string ctprtechnician_SelectAllByRoleid = @"
			-- Select all rows based on a foreign key
			-- selects all rows from the table
			SELECT 
			[id]
			,[name]
			,[designationid]
			,[roleid]
			FROM [dbo].[technician]
			WHERE 
			[roleid] = @roleid OR ([roleid] IS NULL AND @roleid IS NULL)
			";

		internal static string ctprtechnician_SelectAllByRoleidCount = @"
			-- Get count of rows returnable by this query
			-- selects count of all rows from the table
			SELECT COUNT(*)
			FROM [dbo].[technician]
			WHERE 
			[roleid] = @roleid OR ([roleid] IS NULL AND @roleid IS NULL)
			";

		internal static string ctprtechnician_DeleteAllByRoleid = @"
			
			-- delete all matching from the table
			DELETE [dbo].[technician]
			WHERE 
			[roleid] = @roleid OR ([roleid] IS NULL AND @roleid IS NULL)
			";

		internal static string ctprtechnician_InsertOne = @"
			-- Insert a new row
			-- inserts a new row into the table
			INSERT [dbo].[technician]
			(
			[name]
			,[designationid]
			,[roleid]
			)
			VALUES
			(
			@name
			,@designationid
			,@roleid
			)
			SELECT 
			@id = [id]
			,@name = [name]
			,@designationid = [designationid]
			,@roleid = [roleid]
			FROM [dbo].[technician]
			WHERE 
			id = SCOPE_IDENTITY()
			";

		internal static string ctprtechnician_SelectAll = @"
			-- Select All rows
			-- selects all rows from the table
			SELECT 
			[id]
			,[name]
			,[designationid]
			,[roleid]
			FROM [dbo].[technician]
			";

		internal static string ctprtechnician_SelectAllCount = @"
			
			-- selects count of all rows from the table
			SELECT COUNT(*)
			FROM [dbo].[technician]
			";

		internal static string ctprtechnician_SelectAllBySearchFields = @"
			
			-- selects all rows from the table according to search criteria
			SELECT 
			[id],
			[name],
			[designationid],
			[roleid]
			FROM [dbo].[technician]
			WHERE 
			([id] LIKE @id OR @id is null)
			AND ([name] LIKE @name OR @name is null)
			AND ([designationid] LIKE @designationid OR @designationid is null)
			AND ([roleid] LIKE @roleid OR @roleid is null)
			";

		internal static string ctprtechnician_SelectAllBySearchFieldsCount = @"
			-- Get count of rows returnable by this query
			-- selects count of all rows from the table according to search criteria
			SELECT COUNT(*)
			FROM [dbo].[technician]
			WHERE 
			([id] LIKE @id OR @id is null)
			AND ([name] LIKE @name OR @name is null)
			AND ([designationid] LIKE @designationid OR @designationid is null)
			AND ([roleid] LIKE @roleid OR @roleid is null)
			";

		internal static string ctprtechnician_UpdateOne = @"
			-- Update one row based on the primary key(s)
			-- updates a row in the table based on the primary key
			
			UPDATE [dbo].[technician]
			SET
			[name] = @name
			,[designationid] = @designationid
			,[roleid] = @roleid
			WHERE 
			[id] = @id
			SELECT 
			@id = [id]
			,@name = [name]
			,@designationid = [designationid]
			,@roleid = [roleid]
			FROM [dbo].[technician]
			WHERE 
			[id] = @id
			";

	}
}
#endregion
