/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
**************************************************************/

using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;
using System.Configuration;
using System.Collections.Generic;

namespace HelpDeskManager.Data
{
	public partial class HelpDesk_BaseData : IDisposable
	{
		#region members
		protected HelpDesk_TxConnectionProvider _connectionProvider;
		static string _staticConnectionString;
		bool _isDisposed = false;
		#endregion

		#region initialisation
		public HelpDesk_BaseData()
		{
			Init();
		}

		private void Init()
		{
		}
		#endregion

		#region disposable interface support
		public void Dispose()
		{
			Dispose(true);
			GC.SuppressFinalize(this);
		}

		protected virtual void Dispose(bool isDisposing)
		{
			if(!_isDisposed)
			{
				if(isDisposing)
				{
					if(_connectionProvider != null)
					{
						((IDisposable)_connectionProvider).Dispose();
						_connectionProvider = null;
					}
				}
			}
			_isDisposed = true;
		}
		#endregion

		#region connection support
		public static SqlConnection StaticSqlConnection
		{
			get
			{
				SqlConnection staticConnection = new SqlConnection();
				staticConnection.ConnectionString = StaticConnectionString;
				return staticConnection;
			}
		}

		public virtual HelpDesk_TxConnectionProvider ConnectionProvider
		{
			set
			{
				if(value == null)
					throw new Exception("Connection provider cannot be null");
				
				_connectionProvider = value;
			}
		}

		public static string StaticConnectionString
		{
			set { _staticConnectionString = value; }
			get
			{
				if (!string.IsNullOrEmpty(_staticConnectionString))
					return _staticConnectionString;
				
				AppSettingsReader configReader = new AppSettingsReader();
				return (string)configReader.GetValue("3cbe436c-0339-44e6-9a51-7ec6e80093ea", typeof(string));
			}
		}
		#endregion

	}
}
