/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using HelpDeskManager.Business;

namespace HelpDeskManager.Wcf
{
	#region BODepartmentSvc Interface
	[ServiceContract]
	public partial interface IBODepartmentSvc
	{
		///<Summary>
		///GetBODepartment
		///This method returns one BODepartment object by primary key
		///</Summary>
		///<returns>
		///BODepartment
		///</returns>
		///<parameters>
		///Int32 id
		///</parameters>
		[OperationContract]
		BODepartment GetDepartment(Int32 id);

		///<Summary>
		///SaveNewDepartment
		///This method saves one Department record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void SaveNewDepartment(BODepartment boDepartment);

		///<Summary>
		///Update
		///This method updates one Department record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BODepartment
		///</parameters>
		[OperationContract]
		void UpdateDepartment(BODepartment boDepartment);

		///<Summary>
		///Delete
		///This method deletes one Department record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteDepartment(Int32 id);

		///<Summary>
		///DepartmentCollection
		///This method returns the population of BODepartment objects
		///</Summary>
		///<returns>
		///IList[BODepartment]
		///</returns>
		///<parameters>
		///BODepartment
		///</parameters>
		[OperationContract]
		IList<BODepartment> DepartmentCollection();
		
		///<Summary>
		///DepartmentCollectionCount
		///This method returns a count of the population of BODepartment objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		Int32 DepartmentCollectionCount();
		
		///<Summary>
		///DepartmentCollectionFromSearchFields
		///This method returns a collection of BODepartment objects, based on search fields
		///</Summary>
		///<returns>
		///IList[BODepartment]
		///</returns>
		///<parameters>
		///BODepartment
		///</parameters>
		[OperationContract]
		IList<BODepartment> DepartmentCollectionFromSearchFields(BODepartment boDepartment);
		
		///<Summary>
		///DepartmentCollectionFromSearchFieldsCount
		///This method returns a count of its collection of BODepartment objects, based on search fields
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///BODepartment
		///</parameters>
		[OperationContract]
		Int32 DepartmentCollectionFromSearchFieldsCount(BODepartment boDepartment);
		
		///<Summary>
		///Department_IssueCollection
		///This method returns its collection of BOIssue objects
		///</Summary>
		///<returns>
		///IList[BOIssue]
		///</returns>
		///<parameters>
		///BODepartment
		///</parameters>
		[OperationContract]
		IList<BOIssue> Department_IssueCollection(BODepartment boDepartment);
		
		///<Summary>
		///Department_StaffCollection
		///This method returns its collection of BOStaff objects
		///</Summary>
		///<returns>
		///IList[BOStaff]
		///</returns>
		///<parameters>
		///BODepartment
		///</parameters>
		[OperationContract]
		IList<BOStaff> Department_StaffCollection(BODepartment boDepartment);
		
		///<Summary>
		///AddIssueToDepartment
		///This method persists a BOIssue object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOIssue
		///</parameters>
		[OperationContract]
		void AddIssueToDepartment(BODepartment boDepartment, BOIssue _boIssue);
		
		///<Summary>
		///DeleteAllIssueFromDepartment
		///This method deletes all BOIssue objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteAllIssueFromDepartment(BODepartment boDepartment);
		
		///<Summary>
		///AddStaffToDepartment
		///This method persists a BOStaff object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOStaff
		///</parameters>
		[OperationContract]
		void AddStaffToDepartment(BODepartment boDepartment, BOStaff _boStaff);
		
		///<Summary>
		///DeleteAllStaffFromDepartment
		///This method deletes all BOStaff objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteAllStaffFromDepartment(BODepartment boDepartment);
		

	}
	#endregion

}
