/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using HelpDeskManager.Business;

namespace HelpDeskManager.Wcf
{
	#region BODesignationSvc Interface
	[ServiceContract]
	public partial interface IBODesignationSvc
	{
		///<Summary>
		///GetBODesignation
		///This method returns one BODesignation object by primary key
		///</Summary>
		///<returns>
		///BODesignation
		///</returns>
		///<parameters>
		///Int32 id
		///</parameters>
		[OperationContract]
		BODesignation GetDesignation(Int32 id);

		///<Summary>
		///SaveNewDesignation
		///This method saves one Designation record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void SaveNewDesignation(BODesignation boDesignation);

		///<Summary>
		///Update
		///This method updates one Designation record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BODesignation
		///</parameters>
		[OperationContract]
		void UpdateDesignation(BODesignation boDesignation);

		///<Summary>
		///Delete
		///This method deletes one Designation record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteDesignation(Int32 id);

		///<Summary>
		///DesignationCollection
		///This method returns the population of BODesignation objects
		///</Summary>
		///<returns>
		///IList[BODesignation]
		///</returns>
		///<parameters>
		///BODesignation
		///</parameters>
		[OperationContract]
		IList<BODesignation> DesignationCollection();
		
		///<Summary>
		///DesignationCollectionCount
		///This method returns a count of the population of BODesignation objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		Int32 DesignationCollectionCount();
		
		///<Summary>
		///DesignationCollectionFromSearchFields
		///This method returns a collection of BODesignation objects, based on search fields
		///</Summary>
		///<returns>
		///IList[BODesignation]
		///</returns>
		///<parameters>
		///BODesignation
		///</parameters>
		[OperationContract]
		IList<BODesignation> DesignationCollectionFromSearchFields(BODesignation boDesignation);
		
		///<Summary>
		///DesignationCollectionFromSearchFieldsCount
		///This method returns a count of its collection of BODesignation objects, based on search fields
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///BODesignation
		///</parameters>
		[OperationContract]
		Int32 DesignationCollectionFromSearchFieldsCount(BODesignation boDesignation);
		
		///<Summary>
		///Designation_StaffCollection
		///This method returns its collection of BOStaff objects
		///</Summary>
		///<returns>
		///IList[BOStaff]
		///</returns>
		///<parameters>
		///BODesignation
		///</parameters>
		[OperationContract]
		IList<BOStaff> Designation_StaffCollection(BODesignation boDesignation);
		
		///<Summary>
		///Designation_TechnicianCollection
		///This method returns its collection of BOTechnician objects
		///</Summary>
		///<returns>
		///IList[BOTechnician]
		///</returns>
		///<parameters>
		///BODesignation
		///</parameters>
		[OperationContract]
		IList<BOTechnician> Designation_TechnicianCollection(BODesignation boDesignation);
		
		///<Summary>
		///AddStaffToDesignation
		///This method persists a BOStaff object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOStaff
		///</parameters>
		[OperationContract]
		void AddStaffToDesignation(BODesignation boDesignation, BOStaff _boStaff);
		
		///<Summary>
		///DeleteAllStaffFromDesignation
		///This method deletes all BOStaff objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteAllStaffFromDesignation(BODesignation boDesignation);
		
		///<Summary>
		///AddTechnicianToDesignation
		///This method persists a BOTechnician object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOTechnician
		///</parameters>
		[OperationContract]
		void AddTechnicianToDesignation(BODesignation boDesignation, BOTechnician _boTechnician);
		
		///<Summary>
		///DeleteAllTechnicianFromDesignation
		///This method deletes all BOTechnician objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteAllTechnicianFromDesignation(BODesignation boDesignation);
		

	}
	#endregion

}
