/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using HelpDeskManager.Business;

namespace HelpDeskManager.Wcf
{
	#region BOIssuetypeSvc Interface
	[ServiceContract]
	public partial interface IBOIssuetypeSvc
	{
		///<Summary>
		///GetBOIssuetype
		///This method returns one BOIssuetype object by primary key
		///</Summary>
		///<returns>
		///BOIssuetype
		///</returns>
		///<parameters>
		///Int32 id
		///</parameters>
		[OperationContract]
		BOIssuetype GetIssuetype(Int32 id);

		///<Summary>
		///SaveNewIssuetype
		///This method saves one Issuetype record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void SaveNewIssuetype(BOIssuetype boIssuetype);

		///<Summary>
		///Update
		///This method updates one Issuetype record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOIssuetype
		///</parameters>
		[OperationContract]
		void UpdateIssuetype(BOIssuetype boIssuetype);

		///<Summary>
		///Delete
		///This method deletes one Issuetype record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteIssuetype(Int32 id);

		///<Summary>
		///IssuetypeCollection
		///This method returns the population of BOIssuetype objects
		///</Summary>
		///<returns>
		///IList[BOIssuetype]
		///</returns>
		///<parameters>
		///BOIssuetype
		///</parameters>
		[OperationContract]
		IList<BOIssuetype> IssuetypeCollection();
		
		///<Summary>
		///IssuetypeCollectionCount
		///This method returns a count of the population of BOIssuetype objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		Int32 IssuetypeCollectionCount();
		
		///<Summary>
		///IssuetypeCollectionFromSearchFields
		///This method returns a collection of BOIssuetype objects, based on search fields
		///</Summary>
		///<returns>
		///IList[BOIssuetype]
		///</returns>
		///<parameters>
		///BOIssuetype
		///</parameters>
		[OperationContract]
		IList<BOIssuetype> IssuetypeCollectionFromSearchFields(BOIssuetype boIssuetype);
		
		///<Summary>
		///IssuetypeCollectionFromSearchFieldsCount
		///This method returns a count of its collection of BOIssuetype objects, based on search fields
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///BOIssuetype
		///</parameters>
		[OperationContract]
		Int32 IssuetypeCollectionFromSearchFieldsCount(BOIssuetype boIssuetype);
		
		///<Summary>
		///Issuetype_IssueCollection
		///This method returns its collection of BOIssue objects
		///</Summary>
		///<returns>
		///IList[BOIssue]
		///</returns>
		///<parameters>
		///BOIssuetype
		///</parameters>
		[OperationContract]
		IList<BOIssue> Issuetype_IssueCollection(BOIssuetype boIssuetype);
		
		///<Summary>
		///AddIssueToIssuetype
		///This method persists a BOIssue object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOIssue
		///</parameters>
		[OperationContract]
		void AddIssueToIssuetype(BOIssuetype boIssuetype, BOIssue _boIssue);
		
		///<Summary>
		///DeleteAllIssueFromIssuetype
		///This method deletes all BOIssue objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteAllIssueFromIssuetype(BOIssuetype boIssuetype);
		

	}
	#endregion

}
