/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using HelpDeskManager.Business;

namespace HelpDeskManager.Wcf
{
	#region BOIssueStatusSvc Interface
	[ServiceContract]
	public partial interface IBOIssueStatusSvc
	{
		///<Summary>
		///GetBOIssueStatus
		///This method returns one BOIssueStatus object by primary key
		///</Summary>
		///<returns>
		///BOIssueStatus
		///</returns>
		///<parameters>
		///Int32 id
		///</parameters>
		[OperationContract]
		BOIssueStatus GetIssueStatus(Int32 id);

		///<Summary>
		///SaveNewIssueStatus
		///This method saves one IssueStatus record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void SaveNewIssueStatus(BOIssueStatus boIssueStatus);

		///<Summary>
		///Update
		///This method updates one IssueStatus record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOIssueStatus
		///</parameters>
		[OperationContract]
		void UpdateIssueStatus(BOIssueStatus boIssueStatus);

		///<Summary>
		///Delete
		///This method deletes one IssueStatus record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteIssueStatus(Int32 id);

		///<Summary>
		///IssueStatusCollection
		///This method returns the population of BOIssueStatus objects
		///</Summary>
		///<returns>
		///IList[BOIssueStatus]
		///</returns>
		///<parameters>
		///BOIssueStatus
		///</parameters>
		[OperationContract]
		IList<BOIssueStatus> IssueStatusCollection();
		
		///<Summary>
		///IssueStatusCollectionCount
		///This method returns a count of the population of BOIssueStatus objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		Int32 IssueStatusCollectionCount();
		
		///<Summary>
		///IssueStatusCollectionFromSearchFields
		///This method returns a collection of BOIssueStatus objects, based on search fields
		///</Summary>
		///<returns>
		///IList[BOIssueStatus]
		///</returns>
		///<parameters>
		///BOIssueStatus
		///</parameters>
		[OperationContract]
		IList<BOIssueStatus> IssueStatusCollectionFromSearchFields(BOIssueStatus boIssueStatus);
		
		///<Summary>
		///IssueStatusCollectionFromSearchFieldsCount
		///This method returns a count of its collection of BOIssueStatus objects, based on search fields
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///BOIssueStatus
		///</parameters>
		[OperationContract]
		Int32 IssueStatusCollectionFromSearchFieldsCount(BOIssueStatus boIssueStatus);
		
		///<Summary>
		///IssueStatus_IssueCollection
		///This method returns its collection of BOIssue objects
		///</Summary>
		///<returns>
		///IList[BOIssue]
		///</returns>
		///<parameters>
		///BOIssueStatus
		///</parameters>
		[OperationContract]
		IList<BOIssue> IssueStatus_IssueCollection(BOIssueStatus boIssueStatus);
		
		///<Summary>
		///AddIssueToIssueStatus
		///This method persists a BOIssue object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOIssue
		///</parameters>
		[OperationContract]
		void AddIssueToIssueStatus(BOIssueStatus boIssueStatus, BOIssue _boIssue);
		
		///<Summary>
		///DeleteAllIssueFromIssueStatus
		///This method deletes all BOIssue objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteAllIssueFromIssueStatus(BOIssueStatus boIssueStatus);
		

	}
	#endregion

}
