/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using HelpDeskManager.Business;

namespace HelpDeskManager.Wcf
{
	#region BOIssueSvc Interface
	[ServiceContract]
	public partial interface IBOIssueSvc
	{
		///<Summary>
		///SaveNewIssue
		///This method saves one Issue record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void SaveNewIssue(BOIssue boIssue);

		///<Summary>
		///IssueCollection
		///This method returns the population of BOIssue objects
		///</Summary>
		///<returns>
		///IList[BOIssue]
		///</returns>
		///<parameters>
		///BOIssue
		///</parameters>
		[OperationContract]
		IList<BOIssue> IssueCollection();
		
		///<Summary>
		///IssueCollectionCount
		///This method returns a count of the population of BOIssue objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		Int32 IssueCollectionCount();
		
		///<Summary>
		///IssueCollectionFromSearchFields
		///This method returns a collection of BOIssue objects, based on search fields
		///</Summary>
		///<returns>
		///IList[BOIssue]
		///</returns>
		///<parameters>
		///BOIssue
		///</parameters>
		[OperationContract]
		IList<BOIssue> IssueCollectionFromSearchFields(BOIssue boIssue);
		
		///<Summary>
		///IssueCollectionFromSearchFieldsCount
		///This method returns a count of its collection of BOIssue objects, based on search fields
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///BOIssue
		///</parameters>
		[OperationContract]
		Int32 IssueCollectionFromSearchFieldsCount(BOIssue boIssue);
		

	}
	#endregion

}
