/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using HelpDeskManager.Business;

namespace HelpDeskManager.Wcf
{
	#region BORoleSvc Interface
	[ServiceContract]
	public partial interface IBORoleSvc
	{
		///<Summary>
		///GetBORole
		///This method returns one BORole object by primary key
		///</Summary>
		///<returns>
		///BORole
		///</returns>
		///<parameters>
		///Int32 id
		///</parameters>
		[OperationContract]
		BORole GetRole(Int32 id);

		///<Summary>
		///SaveNewRole
		///This method saves one Role record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void SaveNewRole(BORole boRole);

		///<Summary>
		///Update
		///This method updates one Role record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BORole
		///</parameters>
		[OperationContract]
		void UpdateRole(BORole boRole);

		///<Summary>
		///Delete
		///This method deletes one Role record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteRole(Int32 id);

		///<Summary>
		///RoleCollection
		///This method returns the population of BORole objects
		///</Summary>
		///<returns>
		///IList[BORole]
		///</returns>
		///<parameters>
		///BORole
		///</parameters>
		[OperationContract]
		IList<BORole> RoleCollection();
		
		///<Summary>
		///RoleCollectionCount
		///This method returns a count of the population of BORole objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		Int32 RoleCollectionCount();
		
		///<Summary>
		///RoleCollectionFromSearchFields
		///This method returns a collection of BORole objects, based on search fields
		///</Summary>
		///<returns>
		///IList[BORole]
		///</returns>
		///<parameters>
		///BORole
		///</parameters>
		[OperationContract]
		IList<BORole> RoleCollectionFromSearchFields(BORole boRole);
		
		///<Summary>
		///RoleCollectionFromSearchFieldsCount
		///This method returns a count of its collection of BORole objects, based on search fields
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///BORole
		///</parameters>
		[OperationContract]
		Int32 RoleCollectionFromSearchFieldsCount(BORole boRole);
		
		///<Summary>
		///Role_TechnicianCollection
		///This method returns its collection of BOTechnician objects
		///</Summary>
		///<returns>
		///IList[BOTechnician]
		///</returns>
		///<parameters>
		///BORole
		///</parameters>
		[OperationContract]
		IList<BOTechnician> Role_TechnicianCollection(BORole boRole);
		
		///<Summary>
		///AddTechnicianToRole
		///This method persists a BOTechnician object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOTechnician
		///</parameters>
		[OperationContract]
		void AddTechnicianToRole(BORole boRole, BOTechnician _boTechnician);
		
		///<Summary>
		///DeleteAllTechnicianFromRole
		///This method deletes all BOTechnician objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteAllTechnicianFromRole(BORole boRole);
		

	}
	#endregion

}
