/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using HelpDeskManager.Business;

namespace HelpDeskManager.Wcf
{
	#region BOStaffSvc Interface
	[ServiceContract]
	public partial interface IBOStaffSvc
	{
		///<Summary>
		///GetBOStaff
		///This method returns one BOStaff object by primary key
		///</Summary>
		///<returns>
		///BOStaff
		///</returns>
		///<parameters>
		///Int32 id
		///</parameters>
		[OperationContract]
		BOStaff GetStaff(Int32 id);

		///<Summary>
		///SaveNewStaff
		///This method saves one Staff record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void SaveNewStaff(BOStaff boStaff);

		///<Summary>
		///Update
		///This method updates one Staff record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOStaff
		///</parameters>
		[OperationContract]
		void UpdateStaff(BOStaff boStaff);

		///<Summary>
		///Delete
		///This method deletes one Staff record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteStaff(Int32 id);

		///<Summary>
		///StaffCollection
		///This method returns the population of BOStaff objects
		///</Summary>
		///<returns>
		///IList[BOStaff]
		///</returns>
		///<parameters>
		///BOStaff
		///</parameters>
		[OperationContract]
		IList<BOStaff> StaffCollection();
		
		///<Summary>
		///StaffCollectionCount
		///This method returns a count of the population of BOStaff objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		Int32 StaffCollectionCount();
		
		///<Summary>
		///StaffCollectionFromSearchFields
		///This method returns a collection of BOStaff objects, based on search fields
		///</Summary>
		///<returns>
		///IList[BOStaff]
		///</returns>
		///<parameters>
		///BOStaff
		///</parameters>
		[OperationContract]
		IList<BOStaff> StaffCollectionFromSearchFields(BOStaff boStaff);
		
		///<Summary>
		///StaffCollectionFromSearchFieldsCount
		///This method returns a count of its collection of BOStaff objects, based on search fields
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///BOStaff
		///</parameters>
		[OperationContract]
		Int32 StaffCollectionFromSearchFieldsCount(BOStaff boStaff);
		
		///<Summary>
		///Staff_IssueCollection
		///This method returns its collection of BOIssue objects
		///</Summary>
		///<returns>
		///IList[BOIssue]
		///</returns>
		///<parameters>
		///BOStaff
		///</parameters>
		[OperationContract]
		IList<BOIssue> Staff_IssueCollection(BOStaff boStaff);
		
		///<Summary>
		///AddIssueToStaff
		///This method persists a BOIssue object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOIssue
		///</parameters>
		[OperationContract]
		void AddIssueToStaff(BOStaff boStaff, BOIssue _boIssue);
		
		///<Summary>
		///DeleteAllIssueFromStaff
		///This method deletes all BOIssue objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteAllIssueFromStaff(BOStaff boStaff);
		

	}
	#endregion

}
