/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using HelpDeskManager.Business;

namespace HelpDeskManager.Wcf
{
	#region BOTechnicianSvc Interface
	[ServiceContract]
	public partial interface IBOTechnicianSvc
	{
		///<Summary>
		///GetBOTechnician
		///This method returns one BOTechnician object by primary key
		///</Summary>
		///<returns>
		///BOTechnician
		///</returns>
		///<parameters>
		///Int32 id
		///</parameters>
		[OperationContract]
		BOTechnician GetTechnician(Int32 id);

		///<Summary>
		///SaveNewTechnician
		///This method saves one Technician record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void SaveNewTechnician(BOTechnician boTechnician);

		///<Summary>
		///Update
		///This method updates one Technician record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOTechnician
		///</parameters>
		[OperationContract]
		void UpdateTechnician(BOTechnician boTechnician);

		///<Summary>
		///Delete
		///This method deletes one Technician record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteTechnician(Int32 id);

		///<Summary>
		///TechnicianCollection
		///This method returns the population of BOTechnician objects
		///</Summary>
		///<returns>
		///IList[BOTechnician]
		///</returns>
		///<parameters>
		///BOTechnician
		///</parameters>
		[OperationContract]
		IList<BOTechnician> TechnicianCollection();
		
		///<Summary>
		///TechnicianCollectionCount
		///This method returns a count of the population of BOTechnician objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		Int32 TechnicianCollectionCount();
		
		///<Summary>
		///TechnicianCollectionFromSearchFields
		///This method returns a collection of BOTechnician objects, based on search fields
		///</Summary>
		///<returns>
		///IList[BOTechnician]
		///</returns>
		///<parameters>
		///BOTechnician
		///</parameters>
		[OperationContract]
		IList<BOTechnician> TechnicianCollectionFromSearchFields(BOTechnician boTechnician);
		
		///<Summary>
		///TechnicianCollectionFromSearchFieldsCount
		///This method returns a count of its collection of BOTechnician objects, based on search fields
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///BOTechnician
		///</parameters>
		[OperationContract]
		Int32 TechnicianCollectionFromSearchFieldsCount(BOTechnician boTechnician);
		
		///<Summary>
		///Technician_IssueCollection
		///This method returns its collection of BOIssue objects
		///</Summary>
		///<returns>
		///IList[BOIssue]
		///</returns>
		///<parameters>
		///BOTechnician
		///</parameters>
		[OperationContract]
		IList<BOIssue> Technician_IssueCollection(BOTechnician boTechnician);
		
		///<Summary>
		///Technician_LoginCollection
		///This method returns its collection of BOLogin objects
		///</Summary>
		///<returns>
		///IList[BOLogin]
		///</returns>
		///<parameters>
		///BOTechnician
		///</parameters>
		[OperationContract]
		IList<BOLogin> Technician_LoginCollection(BOTechnician boTechnician);
		
		///<Summary>
		///Technician_VisitationCollection
		///This method returns its collection of BOVisitation objects
		///</Summary>
		///<returns>
		///IList[BOVisitation]
		///</returns>
		///<parameters>
		///BOTechnician
		///</parameters>
		[OperationContract]
		IList<BOVisitation> Technician_VisitationCollection(BOTechnician boTechnician);
		
		///<Summary>
		///AddIssueToTechnician
		///This method persists a BOIssue object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOIssue
		///</parameters>
		[OperationContract]
		void AddIssueToTechnician(BOTechnician boTechnician, BOIssue _boIssue);
		
		///<Summary>
		///DeleteAllIssueFromTechnician
		///This method deletes all BOIssue objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteAllIssueFromTechnician(BOTechnician boTechnician);
		
		///<Summary>
		///AddLoginToTechnician
		///This method persists a BOLogin object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOLogin
		///</parameters>
		[OperationContract]
		void AddLoginToTechnician(BOTechnician boTechnician, BOLogin _boLogin);
		
		///<Summary>
		///DeleteAllLoginFromTechnician
		///This method deletes all BOLogin objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteAllLoginFromTechnician(BOTechnician boTechnician);
		
		///<Summary>
		///AddVisitationToTechnician
		///This method persists a BOVisitation object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOVisitation
		///</parameters>
		[OperationContract]
		void AddVisitationToTechnician(BOTechnician boTechnician, BOVisitation _boVisitation);
		
		///<Summary>
		///DeleteAllVisitationFromTechnician
		///This method deletes all BOVisitation objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteAllVisitationFromTechnician(BOTechnician boTechnician);
		

	}
	#endregion

}
