/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using HelpDeskManager.Business;

namespace HelpDeskManager.Wcf
{
	#region BOVisitationSvc Interface
	[ServiceContract]
	public partial interface IBOVisitationSvc
	{
		///<Summary>
		///GetBOVisitation
		///This method returns one BOVisitation object by primary key
		///</Summary>
		///<returns>
		///BOVisitation
		///</returns>
		///<parameters>
		///Int32 id
		///</parameters>
		[OperationContract]
		BOVisitation GetVisitation(Int32 id);

		///<Summary>
		///SaveNewVisitation
		///This method saves one Visitation record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void SaveNewVisitation(BOVisitation boVisitation);

		///<Summary>
		///Update
		///This method updates one Visitation record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOVisitation
		///</parameters>
		[OperationContract]
		void UpdateVisitation(BOVisitation boVisitation);

		///<Summary>
		///Delete
		///This method deletes one Visitation record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		void DeleteVisitation(Int32 id);

		///<Summary>
		///VisitationCollection
		///This method returns the population of BOVisitation objects
		///</Summary>
		///<returns>
		///IList[BOVisitation]
		///</returns>
		///<parameters>
		///BOVisitation
		///</parameters>
		[OperationContract]
		IList<BOVisitation> VisitationCollection();
		
		///<Summary>
		///VisitationCollectionCount
		///This method returns a count of the population of BOVisitation objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		[OperationContract]
		Int32 VisitationCollectionCount();
		
		///<Summary>
		///VisitationCollectionFromSearchFields
		///This method returns a collection of BOVisitation objects, based on search fields
		///</Summary>
		///<returns>
		///IList[BOVisitation]
		///</returns>
		///<parameters>
		///BOVisitation
		///</parameters>
		[OperationContract]
		IList<BOVisitation> VisitationCollectionFromSearchFields(BOVisitation boVisitation);
		
		///<Summary>
		///VisitationCollectionFromSearchFieldsCount
		///This method returns a count of its collection of BOVisitation objects, based on search fields
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///BOVisitation
		///</parameters>
		[OperationContract]
		Int32 VisitationCollectionFromSearchFieldsCount(BOVisitation boVisitation);
		

	}
	#endregion

}
