/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using HelpDeskManager.Business;

namespace HelpDeskManager.Wcf
{
	#region HelpDeskManagerService Interface
	[ServiceContract]
	public partial interface IHelpDeskManagerService  : 
		IBODepartmentSvc
		,IBODesignationSvc
		,IBOIssueSvc
		,IBOIssueStatusSvc
		,IBOIssuetypeSvc
		,IBOLoginSvc
		,IBORoleSvc
		,IBOStaffSvc
		,IBOTechnicianSvc
		,IBOVisitationSvc
	{
		/*auto generated interface list*/
	}
	#endregion

}
