/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using HelpDeskManager.Data;

namespace HelpDeskManager.Business
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOIssueStatus.
	///It maintains a collection of BOIssue objects.
	///</Summary>
	[DataContract]
	public partial class BOIssueStatus : HelpDesk_BaseBusiness
	{
		#region member variables
		protected Int32? _id;
		protected string _status;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		List<BOIssue> _boIssueCollection;
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOIssueStatus()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int32 id
		///</parameters>
		public BOIssueStatus(Int32 id)
		{
			try
			{
				DAOIssueStatus daoIssueStatus = DAOIssueStatus.SelectOne(id);
				_id = daoIssueStatus.Id;
				_status = daoIssueStatus.Status;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOIssueStatus
		///</parameters>
		protected internal BOIssueStatus(DAOIssueStatus daoIssueStatus)
		{
			try
			{
				_id = daoIssueStatus.Id;
				_status = daoIssueStatus.Status;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new IssueStatus record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DAOIssueStatus daoIssueStatus = new DAOIssueStatus();
			RegisterDataObject(daoIssueStatus);
			BeginTransaction("savenewBOIssueStatus");
			try
			{
				daoIssueStatus.Status = _status;
				daoIssueStatus.Insert();
				CommitTransaction();
				
				_id = daoIssueStatus.Id;
				_status = daoIssueStatus.Status;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("savenewBOIssueStatus");
				throw;
			}
		}
		
		///<Summary>
		///Update
		///This method updates one IssueStatus record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOIssueStatus
		///</parameters>
		public virtual void Update()
		{
			DAOIssueStatus daoIssueStatus = new DAOIssueStatus();
			RegisterDataObject(daoIssueStatus);
			BeginTransaction("updateBOIssueStatus");
			try
			{
				daoIssueStatus.Id = _id;
				daoIssueStatus.Status = _status;
				daoIssueStatus.Update();
				CommitTransaction();
				
				_id = daoIssueStatus.Id;
				_status = daoIssueStatus.Status;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("updateBOIssueStatus");
				throw;
			}
		}
		///<Summary>
		///Delete
		///This method deletes one IssueStatus record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DAOIssueStatus daoIssueStatus = new DAOIssueStatus();
			RegisterDataObject(daoIssueStatus);
			BeginTransaction("deleteBOIssueStatus");
			try
			{
				daoIssueStatus.Id = _id;
				daoIssueStatus.Delete();
				CommitTransaction();
			}
			catch
			{
				RollbackTransaction("deleteBOIssueStatus");
				throw;
			}
		}
		
		///<Summary>
		///IssueStatusCollection
		///This method returns the collection of BOIssueStatus objects
		///</Summary>
		///<returns>
		///List[BOIssueStatus]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BOIssueStatus> IssueStatusCollection()
		{
			try
			{
				IList<BOIssueStatus> boIssueStatusCollection = new List<BOIssueStatus>();
				IList<DAOIssueStatus> daoIssueStatusCollection = DAOIssueStatus.SelectAll();
			
				foreach(DAOIssueStatus daoIssueStatus in daoIssueStatusCollection)
					boIssueStatusCollection.Add(new BOIssueStatus(daoIssueStatus));
			
				return boIssueStatusCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///IssueStatusCollectionCount
		///This method returns the collection count of BOIssueStatus objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 IssueStatusCollectionCount()
		{
			try
			{
				Int32 objCount = DAOIssueStatus.SelectAllCount();
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///IssueStatusCollectionFromSearchFields
		///This method returns the collection of BOIssueStatus objects, filtered by a search object
		///</Summary>
		///<returns>
		///List<BOIssueStatus>
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BOIssueStatus> IssueStatusCollectionFromSearchFields(BOIssueStatus boIssueStatus)
		{
			try
			{
				IList<BOIssueStatus> boIssueStatusCollection = new List<BOIssueStatus>();
				DAOIssueStatus daoIssueStatus = new DAOIssueStatus();
				daoIssueStatus.Id = boIssueStatus.Id;
				daoIssueStatus.Status = boIssueStatus.Status;
				IList<DAOIssueStatus> daoIssueStatusCollection = DAOIssueStatus.SelectAllBySearchFields(daoIssueStatus);
			
				foreach(DAOIssueStatus resdaoIssueStatus in daoIssueStatusCollection)
					boIssueStatusCollection.Add(new BOIssueStatus(resdaoIssueStatus));
			
				return boIssueStatusCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///IssueStatusCollectionFromSearchFieldsCount
		///This method returns the collection count of BOIssueStatus objects, filtered by a search object
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 IssueStatusCollectionFromSearchFieldsCount(BOIssueStatus boIssueStatus)
		{
			try
			{
				DAOIssueStatus daoIssueStatus = new DAOIssueStatus();
				daoIssueStatus.Id = boIssueStatus.Id;
				daoIssueStatus.Status = boIssueStatus.Status;
				Int32 objCount = DAOIssueStatus.SelectAllBySearchFieldsCount(daoIssueStatus);
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		///<Summary>
		///IssueCollection
		///This method returns its collection of BOIssue objects
		///</Summary>
		///<returns>
		///IList[BOIssue]
		///</returns>
		///<parameters>
		///BOIssueStatus
		///</parameters>
		public virtual IList<BOIssue> IssueCollection()
		{
			try
			{
				if(_boIssueCollection == null)
					LoadIssueCollection();
				
				return _boIssueCollection.AsReadOnly();
			}
			catch
			{
				throw;
			}
		}
		
		///<Summary>
		///LoadIssueCollection
		///This method loads the internal collection of BOIssue objects from storage. 
		///Call this if you need to ensure the collection is up-to-date (concurrency)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void LoadIssueCollection()
		{
			try
			{
				_boIssueCollection = new List<BOIssue>();
				IList<DAOIssue> daoIssueCollection = DAOIssue.SelectAllByStatusid(_id.Value);
				
				foreach(DAOIssue daoIssue in daoIssueCollection)
					_boIssueCollection.Add(new BOIssue(daoIssue));
			}
			catch
			{
				throw;
			}
		}
		
		///<Summary>
		///AddIssue
		///This method persists a BOIssue object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOIssue
		///</parameters>
		public virtual void AddIssue(BOIssue boIssue)
		{
			DAOIssue daoIssue = new DAOIssue();
			RegisterDataObject(daoIssue);
			BeginTransaction("addIssue");
			try
			{
				daoIssue.Id = boIssue.Id;
				daoIssue.Typeid = boIssue.Typeid;
				daoIssue.Staffid = boIssue.Staffid;
				daoIssue.Departmentid = boIssue.Departmentid;
				daoIssue.Details = boIssue.Details;
				daoIssue.Technicianid = boIssue.Technicianid;
				daoIssue.Remarks = boIssue.Remarks;
				daoIssue.Statusid = _id.Value;
				daoIssue.Insert();
				CommitTransaction();
				
				/*pick up any primary keys, computed values etc*/
				boIssue = new BOIssue(daoIssue);
				if(_boIssueCollection != null)
					_boIssueCollection.Add(boIssue);
			}
			catch
			{
				RollbackTransaction("addIssue");
				throw;
			}
		}
		
		///<Summary>
		///DeleteAllIssue
		///This method deletes all BOIssue objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void DeleteAllIssue()
		{
			RegisterDataObject(null);
			BeginTransaction("deleteAllIssue");
			try
			{
				DAOIssue.DeleteAllByStatusid(ConnectionProvider, _id.Value);
				CommitTransaction();
				if(_boIssueCollection != null)
				{
					_boIssueCollection.Clear();
					_boIssueCollection = null;
				}
			}
			catch
			{
				RollbackTransaction("deleteAllIssue");
				throw;
			}
		}
		
		#endregion

		#region member properties
		
		[DataMember]
		public virtual Int32? Id
		{
			get
			{
				 return _id;
			}
			set
			{
				_id = value;
				_isDirty = true;
			}
		}
		
		[DataMember]
		public virtual string Status
		{
			get
			{
				 return _status;
			}
			set
			{
				_status = value;
				_isDirty = true;
			}
		}
		
		[DataMember]
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		[DataMember]
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
