/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using HelpDeskManager.Data;

namespace HelpDeskManager.Business
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOIssue.
	///</Summary>
	[DataContract]
	public partial class BOIssue : HelpDesk_BaseBusiness
	{
		#region member variables
		protected Int32? _id;
		protected Int32? _typeid;
		protected Int32? _staffid;
		protected Int32? _departmentid;
		protected Int32? _statusid;
		protected string _details;
		protected Int32? _technicianid;
		protected string _remarks;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOIssue()
		{
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOIssue
		///</parameters>
		protected internal BOIssue(DAOIssue daoIssue)
		{
			try
			{
				_id = daoIssue.Id;
				_typeid = daoIssue.Typeid;
				_staffid = daoIssue.Staffid;
				_departmentid = daoIssue.Departmentid;
				_statusid = daoIssue.Statusid;
				_details = daoIssue.Details;
				_technicianid = daoIssue.Technicianid;
				_remarks = daoIssue.Remarks;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new Issue record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DAOIssue daoIssue = new DAOIssue();
			RegisterDataObject(daoIssue);
			BeginTransaction("savenewBOIssue");
			try
			{
				daoIssue.Typeid = _typeid;
				daoIssue.Staffid = _staffid;
				daoIssue.Departmentid = _departmentid;
				daoIssue.Statusid = _statusid;
				daoIssue.Details = _details;
				daoIssue.Technicianid = _technicianid;
				daoIssue.Remarks = _remarks;
				daoIssue.Insert();
				CommitTransaction();
				
				_id = daoIssue.Id;
				_typeid = daoIssue.Typeid;
				_staffid = daoIssue.Staffid;
				_departmentid = daoIssue.Departmentid;
				_statusid = daoIssue.Statusid;
				_details = daoIssue.Details;
				_technicianid = daoIssue.Technicianid;
				_remarks = daoIssue.Remarks;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("savenewBOIssue");
				throw;
			}
		}
		
		
		///<Summary>
		///IssueCollection
		///This method returns the collection of BOIssue objects
		///</Summary>
		///<returns>
		///List[BOIssue]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BOIssue> IssueCollection()
		{
			try
			{
				IList<BOIssue> boIssueCollection = new List<BOIssue>();
				IList<DAOIssue> daoIssueCollection = DAOIssue.SelectAll();
			
				foreach(DAOIssue daoIssue in daoIssueCollection)
					boIssueCollection.Add(new BOIssue(daoIssue));
			
				return boIssueCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///IssueCollectionCount
		///This method returns the collection count of BOIssue objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 IssueCollectionCount()
		{
			try
			{
				Int32 objCount = DAOIssue.SelectAllCount();
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///IssueCollectionFromSearchFields
		///This method returns the collection of BOIssue objects, filtered by a search object
		///</Summary>
		///<returns>
		///List<BOIssue>
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BOIssue> IssueCollectionFromSearchFields(BOIssue boIssue)
		{
			try
			{
				IList<BOIssue> boIssueCollection = new List<BOIssue>();
				DAOIssue daoIssue = new DAOIssue();
				daoIssue.Id = boIssue.Id;
				daoIssue.Typeid = boIssue.Typeid;
				daoIssue.Staffid = boIssue.Staffid;
				daoIssue.Departmentid = boIssue.Departmentid;
				daoIssue.Statusid = boIssue.Statusid;
				daoIssue.Details = boIssue.Details;
				daoIssue.Technicianid = boIssue.Technicianid;
				daoIssue.Remarks = boIssue.Remarks;
				IList<DAOIssue> daoIssueCollection = DAOIssue.SelectAllBySearchFields(daoIssue);
			
				foreach(DAOIssue resdaoIssue in daoIssueCollection)
					boIssueCollection.Add(new BOIssue(resdaoIssue));
			
				return boIssueCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///IssueCollectionFromSearchFieldsCount
		///This method returns the collection count of BOIssue objects, filtered by a search object
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 IssueCollectionFromSearchFieldsCount(BOIssue boIssue)
		{
			try
			{
				DAOIssue daoIssue = new DAOIssue();
				daoIssue.Id = boIssue.Id;
				daoIssue.Typeid = boIssue.Typeid;
				daoIssue.Staffid = boIssue.Staffid;
				daoIssue.Departmentid = boIssue.Departmentid;
				daoIssue.Statusid = boIssue.Statusid;
				daoIssue.Details = boIssue.Details;
				daoIssue.Technicianid = boIssue.Technicianid;
				daoIssue.Remarks = boIssue.Remarks;
				Int32 objCount = DAOIssue.SelectAllBySearchFieldsCount(daoIssue);
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		#endregion

		#region member properties
		
		[DataMember]
		public virtual Int32? Id
		{
			get
			{
				 return _id;
			}
			set
			{
				_id = value;
				_isDirty = true;
			}
		}
		
		[DataMember]
		public virtual Int32? Typeid
		{
			get
			{
				 return _typeid;
			}
			set
			{
				_typeid = value;
				_isDirty = true;
			}
		}
		
		[DataMember]
		public virtual Int32? Staffid
		{
			get
			{
				 return _staffid;
			}
			set
			{
				_staffid = value;
				_isDirty = true;
			}
		}
		
		[DataMember]
		public virtual Int32? Departmentid
		{
			get
			{
				 return _departmentid;
			}
			set
			{
				_departmentid = value;
				_isDirty = true;
			}
		}
		
		[DataMember]
		public virtual Int32? Statusid
		{
			get
			{
				 return _statusid;
			}
			set
			{
				_statusid = value;
				_isDirty = true;
			}
		}
		
		[DataMember]
		public virtual string Details
		{
			get
			{
				 return _details;
			}
			set
			{
				_details = value;
				_isDirty = true;
			}
		}
		
		[DataMember]
		public virtual Int32? Technicianid
		{
			get
			{
				 return _technicianid;
			}
			set
			{
				_technicianid = value;
				_isDirty = true;
			}
		}
		
		[DataMember]
		public virtual string Remarks
		{
			get
			{
				 return _remarks;
			}
			set
			{
				_remarks = value;
				_isDirty = true;
			}
		}
		
		[DataMember]
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		[DataMember]
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
