/*************************************************************
** Class generated by CodeTrigger, Version 4.8.6.1
** This class was generated on 9/16/2016 11:50:03 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using HelpDeskManager.Data;

namespace HelpDeskManager.Business
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOStaff.
	///It maintains a collection of BOIssue objects.
	///</Summary>
	[DataContract]
	public partial class BOStaff : HelpDesk_BaseBusiness
	{
		#region member variables
		protected Int32? _id;
		protected string _name;
		protected Int32? _designationid;
		protected Int32? _departmentid;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		List<BOIssue> _boIssueCollection;
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOStaff()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int32 id
		///</parameters>
		public BOStaff(Int32 id)
		{
			try
			{
				DAOStaff daoStaff = DAOStaff.SelectOne(id);
				_id = daoStaff.Id;
				_name = daoStaff.Name;
				_designationid = daoStaff.Designationid;
				_departmentid = daoStaff.Departmentid;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOStaff
		///</parameters>
		protected internal BOStaff(DAOStaff daoStaff)
		{
			try
			{
				_id = daoStaff.Id;
				_name = daoStaff.Name;
				_designationid = daoStaff.Designationid;
				_departmentid = daoStaff.Departmentid;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new Staff record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DAOStaff daoStaff = new DAOStaff();
			RegisterDataObject(daoStaff);
			BeginTransaction("savenewBOStaff");
			try
			{
				daoStaff.Name = _name;
				daoStaff.Designationid = _designationid;
				daoStaff.Departmentid = _departmentid;
				daoStaff.Insert();
				CommitTransaction();
				
				_id = daoStaff.Id;
				_name = daoStaff.Name;
				_designationid = daoStaff.Designationid;
				_departmentid = daoStaff.Departmentid;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("savenewBOStaff");
				throw;
			}
		}
		
		///<Summary>
		///Update
		///This method updates one Staff record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOStaff
		///</parameters>
		public virtual void Update()
		{
			DAOStaff daoStaff = new DAOStaff();
			RegisterDataObject(daoStaff);
			BeginTransaction("updateBOStaff");
			try
			{
				daoStaff.Id = _id;
				daoStaff.Name = _name;
				daoStaff.Designationid = _designationid;
				daoStaff.Departmentid = _departmentid;
				daoStaff.Update();
				CommitTransaction();
				
				_id = daoStaff.Id;
				_name = daoStaff.Name;
				_designationid = daoStaff.Designationid;
				_departmentid = daoStaff.Departmentid;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("updateBOStaff");
				throw;
			}
		}
		///<Summary>
		///Delete
		///This method deletes one Staff record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DAOStaff daoStaff = new DAOStaff();
			RegisterDataObject(daoStaff);
			BeginTransaction("deleteBOStaff");
			try
			{
				daoStaff.Id = _id;
				daoStaff.Delete();
				CommitTransaction();
			}
			catch
			{
				RollbackTransaction("deleteBOStaff");
				throw;
			}
		}
		
		///<Summary>
		///StaffCollection
		///This method returns the collection of BOStaff objects
		///</Summary>
		///<returns>
		///List[BOStaff]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BOStaff> StaffCollection()
		{
			try
			{
				IList<BOStaff> boStaffCollection = new List<BOStaff>();
				IList<DAOStaff> daoStaffCollection = DAOStaff.SelectAll();
			
				foreach(DAOStaff daoStaff in daoStaffCollection)
					boStaffCollection.Add(new BOStaff(daoStaff));
			
				return boStaffCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///StaffCollectionCount
		///This method returns the collection count of BOStaff objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 StaffCollectionCount()
		{
			try
			{
				Int32 objCount = DAOStaff.SelectAllCount();
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///StaffCollectionFromSearchFields
		///This method returns the collection of BOStaff objects, filtered by a search object
		///</Summary>
		///<returns>
		///List<BOStaff>
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<BOStaff> StaffCollectionFromSearchFields(BOStaff boStaff)
		{
			try
			{
				IList<BOStaff> boStaffCollection = new List<BOStaff>();
				DAOStaff daoStaff = new DAOStaff();
				daoStaff.Id = boStaff.Id;
				daoStaff.Name = boStaff.Name;
				daoStaff.Designationid = boStaff.Designationid;
				daoStaff.Departmentid = boStaff.Departmentid;
				IList<DAOStaff> daoStaffCollection = DAOStaff.SelectAllBySearchFields(daoStaff);
			
				foreach(DAOStaff resdaoStaff in daoStaffCollection)
					boStaffCollection.Add(new BOStaff(resdaoStaff));
			
				return boStaffCollection;
			}
			catch
			{
				throw;
			}
		}
		
		
		///<Summary>
		///StaffCollectionFromSearchFieldsCount
		///This method returns the collection count of BOStaff objects, filtered by a search object
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 StaffCollectionFromSearchFieldsCount(BOStaff boStaff)
		{
			try
			{
				DAOStaff daoStaff = new DAOStaff();
				daoStaff.Id = boStaff.Id;
				daoStaff.Name = boStaff.Name;
				daoStaff.Designationid = boStaff.Designationid;
				daoStaff.Departmentid = boStaff.Departmentid;
				Int32 objCount = DAOStaff.SelectAllBySearchFieldsCount(daoStaff);
				return objCount;
			}
			catch
			{
				throw;
			}
		}
		
		///<Summary>
		///IssueCollection
		///This method returns its collection of BOIssue objects
		///</Summary>
		///<returns>
		///IList[BOIssue]
		///</returns>
		///<parameters>
		///BOStaff
		///</parameters>
		public virtual IList<BOIssue> IssueCollection()
		{
			try
			{
				if(_boIssueCollection == null)
					LoadIssueCollection();
				
				return _boIssueCollection.AsReadOnly();
			}
			catch
			{
				throw;
			}
		}
		
		///<Summary>
		///LoadIssueCollection
		///This method loads the internal collection of BOIssue objects from storage. 
		///Call this if you need to ensure the collection is up-to-date (concurrency)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void LoadIssueCollection()
		{
			try
			{
				_boIssueCollection = new List<BOIssue>();
				IList<DAOIssue> daoIssueCollection = DAOIssue.SelectAllByStaffid(_id.Value);
				
				foreach(DAOIssue daoIssue in daoIssueCollection)
					_boIssueCollection.Add(new BOIssue(daoIssue));
			}
			catch
			{
				throw;
			}
		}
		
		///<Summary>
		///AddIssue
		///This method persists a BOIssue object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOIssue
		///</parameters>
		public virtual void AddIssue(BOIssue boIssue)
		{
			DAOIssue daoIssue = new DAOIssue();
			RegisterDataObject(daoIssue);
			BeginTransaction("addIssue");
			try
			{
				daoIssue.Id = boIssue.Id;
				daoIssue.Typeid = boIssue.Typeid;
				daoIssue.Departmentid = boIssue.Departmentid;
				daoIssue.Statusid = boIssue.Statusid;
				daoIssue.Details = boIssue.Details;
				daoIssue.Technicianid = boIssue.Technicianid;
				daoIssue.Remarks = boIssue.Remarks;
				daoIssue.Staffid = _id.Value;
				daoIssue.Insert();
				CommitTransaction();
				
				/*pick up any primary keys, computed values etc*/
				boIssue = new BOIssue(daoIssue);
				if(_boIssueCollection != null)
					_boIssueCollection.Add(boIssue);
			}
			catch
			{
				RollbackTransaction("addIssue");
				throw;
			}
		}
		
		///<Summary>
		///DeleteAllIssue
		///This method deletes all BOIssue objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void DeleteAllIssue()
		{
			RegisterDataObject(null);
			BeginTransaction("deleteAllIssue");
			try
			{
				DAOIssue.DeleteAllByStaffid(ConnectionProvider, _id.Value);
				CommitTransaction();
				if(_boIssueCollection != null)
				{
					_boIssueCollection.Clear();
					_boIssueCollection = null;
				}
			}
			catch
			{
				RollbackTransaction("deleteAllIssue");
				throw;
			}
		}
		
		#endregion

		#region member properties
		
		[DataMember]
		public virtual Int32? Id
		{
			get
			{
				 return _id;
			}
			set
			{
				_id = value;
				_isDirty = true;
			}
		}
		
		[DataMember]
		public virtual string Name
		{
			get
			{
				 return _name;
			}
			set
			{
				_name = value;
				_isDirty = true;
			}
		}
		
		[DataMember]
		public virtual Int32? Designationid
		{
			get
			{
				 return _designationid;
			}
			set
			{
				_designationid = value;
				_isDirty = true;
			}
		}
		
		[DataMember]
		public virtual Int32? Departmentid
		{
			get
			{
				 return _departmentid;
			}
			set
			{
				_departmentid = value;
				_isDirty = true;
			}
		}
		
		[DataMember]
		public virtual object Repository
		{
			get {	return null;	}
			set	{	}
		}
		
		[DataMember]
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
